/* eslint-disable @typescript-eslint/no-explicit-any */
import type React from "react";

import { Badge, Button, Icon, Image } from "./components/content";
import { Basic, Card, ListView, ListViewItem } from "./components/containers";
import { Box, Col, Divider, Row, Spacer } from "./components/layout";
import { AreaChart, BarChart, Chart, LineChart, PieChart } from "./components/chart";
import { Checkbox, DatePicker, Form, Input, Label, RadioGroup, Select, Textarea } from "./components/forms";
import { Text, Title, Caption, Markdown } from "./components/text";
import { Transition } from "./components/transition";
import { Avatar, Progress } from "./components/extras";
import {
  Animate,
  AnimateItem,
  AnimateGroup,
  AudioPlayer,
  BaseCarousel,
  BaseCarouselItem,
  BaseCarouselMediaItem,
  Bold,
  CardCarousel,
  CardLinkItem,
  Code,
  CotResolvedIcon,
  Debug,
  Each,
  Favicon,
  Flow,
  FlowItem,
  FootballLocationIndicator,
  Grid,
  GridItem,
  Hermes,
  Highlight,
  Inline,
  Italic,
  List,
  ListItem,
  LoadingBlock,
  LoadingDot,
  LoadingIndicator,
  Map,
  Math,
  OverflowRow,
  Popover,
  PopoverContent,
  PopoverTrigger,
  Pressable,
  PulseIndicator,
  Response,
  RunInterval,
  Scope,
  SegmentedControl,
  ShimmerText,
  Show,
  ShowElse,
  Svg,
  Table,
  TableCell,
  TableRow,
  TableSection,
  Underline,
  YouTubeEmbed
} from "./components/dil";
import {
  Accordion,
  Collapsible,
  Menubar,
  ContextMenu,
  Tooltip,
  Toggle,
  ToggleGroup,
  Slider,
  Sheet,
  Drawer,
  Combobox,
  InputOTP,
  Spinner,
  DataTable
} from "./components/advanced";

export type ComponentRegistry = Record<string, React.ComponentType<any>>;

export const widgetRegistry: ComponentRegistry = {
  Animate,
  "Animate.Item": AnimateItem,
  AnimateGroup,
  AudioPlayer,
  Basic,
  BaseCarousel,
  "BaseCarousel.Item": BaseCarouselItem,
  "BaseCarousel.MediaItem": BaseCarouselMediaItem,
  Card,
  CardCarousel,
  CardLinkItem,
  Response,
  Debug,
  Hermes,
  CotResolvedIcon,
  FootballLocationIndicator,
  ListView,
  ListViewItem,
  List,
  "List.Item": ListItem,
  Each,
  Scope,
  Show,
  "Show.Else": ShowElse,
  RunInterval,
  Box,
  Row,
  Col,
  Grid,
  "Grid.Item": GridItem,
  Flow,
  "Flow.Item": FlowItem,
  OverflowRow,
  Pressable,
  Inline,
  Divider,
  Icon,
  Image,
  Favicon,
  Svg,
  Audio: AudioPlayer,
  YouTubeEmbed,
  Map,
  Button,
  Checkbox,
  // Charts
  Chart,
  Table,
  "Table.Row": TableRow,
  "Table.Cell": TableCell,
  "Table.Section": TableSection,
  BarChart,
  LineChart,
  AreaChart,
  PieChart,
  Spacer,
  Select,
  DatePicker,
  Form,
  Input,
  Label,
  RadioGroup,
  Textarea,
  Transition,
  Text,
  Title,
  Caption,
  Bold,
  Italic,
  Underline,
  Code,
  Math,
  Highlight,
  ShimmerText,
  Badge,
  Markdown,
  Avatar,
  Progress,
  Accordion,
  Collapsible,
  Menubar,
  ContextMenu,
  Tooltip,
  Toggle,
  ToggleGroup,
  Slider,
  SegmentedControl,
  Sheet,
  Drawer,
  Popover,
  "Popover.Trigger": PopoverTrigger,
  "Popover.Content": PopoverContent,
  Combobox,
  InputOTP,
  Spinner,
  LoadingBlock,
  LoadingDot,
  LoadingIndicator,
  PulseIndicator,
  DataTable
};
